name: jira_check
on: 
  push:
    branches:
      - jira-checker
      
env:
  atlassian_user: brytboy@github.com
  atlassian_key: 9MGgvvK0k38Sw3zYqDMmA485
  atlassian_url: team-1624462930934.atlassian.net
      
jobs:
  issue-validation:
    runs-on: ubuntu-latest
    steps:
      - id: issue-validation
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          COMMIT_MESSAGE=${COMMIT_MESSAGE#*\[}
          ISSUE=${COMMIT_MESSAGE%\]*}
          if [ $ISSUE == "" ]
          then
            echo "Commit message did not contain a valid JIRA issue key in the expected format: [JIRA-KEY] -- failing operation."
            exit 1
          fi
          ISSUE_STATUS=$(curl -u "${{ env.atlassian_user }}:${{ env.atlassian_key }}" -H "Content-Type:application/json" "https://${{ env.atlassian_url }}/rest/api/2/issue/${ISSUE}" | jq '.fields.status.name')
          echo $ISSUE_STATUS
          if [[ $ISSUE_STATUS == '"To Do"' ]] || [[ $ISSUE_STATUS == '"In Progress"' ]]
          then
            EVENT_MESSAGE="{\"body\":\"New GitHub work has been linked to this issue: https://github.com/BrytBoyCorp/github-actions/commit/${GITHUB_SHA}\"}"
            curl -X POST -u "${{ env.atlassian_user }}:${{ env.atlassian_key }}" -H "Accept:application/json" -H "Content-Type:application/json" -d "${EVENT_MESSAGE}" "https://${{ env.atlassian_url }}/rest/api/2/issue/${ISSUE}/comment"
          else
            echo "JIRA issue does not appear to be in an active sprint. Instead the issue status is: ${ISSUE_STATUS} -- Exiting..."
          fi
             
